log:
    level: debug

title: my.example.com

admin:
    - alice
    - bob

webserver:
    protocol: http
    hostname: localhost:8080
    port: 8080
    debug: false

cookie:
    name: _forward_auth
    secret: P@ssword
    domain: example.com

validity:
    session: 30
    credential: 120

authfile: basic-auth.yml

